// react/ee.09-02-20.01-sg/src/Kalkulacja.js
import { useState } from 'react';

function Kalkulacja() {
    
    let [message, setMessage] = useState("");
    let [liters, setLiters]  = useState({});;
    const [inputs, setInputs] = useState({});
    const handleChange = (event) => {
        const name = event.target.name;
        const value = event.target.value;
        setInputs(values => ({...values, [name]: value}))
      }
    const handleSubmit = (event) => {
        event.preventDefault();
        console.log(inputs);
        liters = setLiters({liters: inputs.spalanie * inputs.dystans /100});
        message = setMessage(`Potrzebujesz: ${liters} litrów paliwa`);
    }
    return (
    <>
        <div id="main">
            <h2>Oblicz, ile litrów musisz zatankowa</h2>
            <form onSubmit={handleSubmit}>
                dystans do przejechania w km:<br />
                <input type="number" name="dystans" id="dystans" value={inputs.dystans || ""} onChange={handleChange} /><br />
                spalanie samochodu w l/100km:<br />
                <input type="number" id="spalanie" name="spalanie" value={inputs.spalanie || ""} onChange={handleChange} /><br />
                <input type="submit" value="oblicz" />
            </form>
            <p>{message}</p>
        </div>
    </>
    );
  }
  
  export default Kalkulacja;

// angular/EE.09-02-20.01-SG/src/app/components/kalkulacja/kalkulacja.component.ts
import { Component } from '@angular/core';
import { NgForm } from '@angular/forms';


@Component({
  selector: 'app-kalkulacja',
  templateUrl: './kalkulacja.component.html',
  styleUrls: ['./kalkulacja.component.css']
})
export class KalkulacjaComponent {
  message: string;
  constructor() {
    this.message = "";
  }
  onSubmit(form1: NgForm) {
    // console.log("OK");
    const dystans = form1.value.dystans;
    const spalanie = form1.value.spalanie;
    // console.log(dystans, spalanie);
    // console.log(typeof dystans, typeof spalanie);
    let liters: number;
    liters = spalanie*dystans/100;
    this.message = `Potrzebujesz: ${liters} litrów paliwa`;
  }
}

<div id="container-right">
    <img src="../../assets/samochod.png" alt="grafika: samochód">
</div>
<div id="main">
    <h2>Oblicz, ile litrów musisz zatankowa</h2>
    <form (ngSubmit)="onSubmit(form1)" #form1="ngForm">
        <label for="dystans">dystans do przejechania w km:</label><br>
        <input type="number" name="dystans" id="dystans" ngModel required><br>
        <label for="spalanie">spalanie samochodu w l/100km:</label><br>
        <input type="number" id="spalanie" name="spalanie" ngModel required><br>
        <input type="submit" value="Oblicz">
    </form>
    {{ message }}
</div>
